version: "3.8"

services:
  image-processor:
    build: .
    ports:
      - "3001:3001"
    networks:
      - my-network

  nginx:
    build: ./etc/nginx
    ports:
      - "8001:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  data:
