version: "3.x.x"
services:
  
  database:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - my-network

  server1:
    image: hallzero/go-server
    env_file: .env
    ports:
      - "3333:3333"
    depends_on:
      - database
    networks:
      - my-network

  server2:
    image: hallzero/go-server
    env_file: .env
    ports:
      - "3334:3333"
    depends_on:
      - database
    networks:
      - my-network

  gateway:
    build: ./etc/nginx
    networks:
      - my-network
    ports:
      - "8000:80"
  
  redis:
    image: redis:latest
    tty: true
    ports:
      - '6379:6379'
    volumes:
            - '.cache/redis:/data'
    healthcheck:
        test: ['CMD', 'redis-cli', 'ping']
        interval: 5s
        timeout: 5s
        retries: 5
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  data:
