version: "3.x.x"
services:
  
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - my-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3333:3333"
    depends_on:
      - database
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  data:
