version: "3.x.x"
services:
  
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - my-network

  server1:
    image: hallzero/go-server
    env_file: .env
    ports:
      - "3333:3333"
    depends_on:
      - database
    networks:
      - my-network

  server2:
    image: hallzero/go-server
    env_file: .env
    ports:
      - "3334:3333"
    depends_on:
      - database
    networks:
      - my-network

  gateway:
    build: ./etc/nginx
    networks:
      - my-network
    ports:
      - "8000:80"

networks:
  my-network:
    driver: bridge

volumes:
  data:
